# Generated by Django 5.1.5 on 2026-01-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
