# Generated by Django 5.1.5 on 2026-01-31 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_date_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='date',
        ),
    ]
