# Generated by Django 5.1.5 on 2026-01-31 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_date_date_date_created_ad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
